- name: Ensure the system group is present
  group:
    name: "{{ service.group }}"
    system: yes
    state: present

- name: Ensure the 'service' system user exists
  user:
    name: "{{ service.name }}"
    shell: /sbin/nologin
    system: yes
    group: "{{ service.group }}"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ service.name }}"
    group: "{{ service.group }}"
  loop:
    - "/var/lib/{{ service.name }}"
    - "/run/{{ service.name }}"

- name: Copy binaries
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: "{{ service.name }}"
    group: "{{ service.group }}"
    mode: 0755
  loop:
    - "files/{{ service.bin_name }}"

- name: Copy service config
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - "files/{{ service.unit_name }}"

- name: Start and enable service
  ansible.builtin.systemd:
    name: "{{ service.name }}"
    state: started
    enabled: true

- name: Ensure service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ service.name }}"
    state: started
    enabled: true

- name: Ensure service is running
  ansible.builtin.uri:
    url: "{{ service.addr }}"
    method: GET
    return_content: yes
  register: service_check
  until: service_check.status == 200
  retries: 5
  delay: 10
