- name: Ensure the system group is present
  group:
    name: "{{ service.group }}"
    system: yes
    state: present

- name: Ensure the system user exists
  user:
    name: "{{ service.name }}"
    shell: /sbin/nologin
    system: yes
    group: "{{ service.group }}"

- name: Copy binaries
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: "{{ service.name }}"
    group: "{{ service.group }}"
    mode: 0755
  loop:
    - "files/{{ service.bin_name }}"

- name: Copy service config
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - "files/{{ service.unit_name }}.service"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ service.name }}"
    group: "{{ service.group }}"
  loop:
    - "/etc/{{ service.name }}"

- name: Copy env file
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ service.name }}"
    owner: "{{ service.name }}"
    group: "{{ service.group }}"
    mode: 0755
  loop:
    - "files/{{ service.env_file }}.env"

- name: Ensure service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ service.unit_name }}"
    state: started
    enabled: true

- name: Ensure service is running
  ansible.builtin.uri:
    url: "{{ service.addr }}"
    method: GET
    return_content: yes
  register: "up_check"
  until: up_check.status == 200
  retries: 5
  delay: 10
