global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    site: prod

remote_write:
  - url: http://localhost:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets:
        - '127.0.0.1:9090'
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - '127.0.0.1:80'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: "node-exporter-cms"
    static_configs:
      - targets:
        - '127.0.0.1:9100'
  - job_name: "mysql-exporter-cms"
    static_configs:
      - targets:
        - '127.0.0.1:9104'